import path from "node:path";
import type { SpecModel, Schema } from "../models.js";
import { cppConstName, cppName, hex, sortById, writeTextFile } from "../util.js";

const banner = `// Generated by axtp-gen. Do not edit manually.\n`;

function enumBlock(name: string, type: string, items: { name: string; id: number }[]): string {
  const width = type.includes("uint8") ? 2 : 4;
  const rows = sortById(items).map((item) => `    ${cppName(item.name)} = ${hex(item.id, width)},`).join("\n");
  return `enum class ${name} : ${type} {\n${rows}\n};`;
}

function fieldType(type: string): string {
  const map: Record<string, string> = {
    uint8: "FieldType::Uint8",
    uint16: "FieldType::Uint16",
    uint32: "FieldType::Uint32",
    uint64: "FieldType::Uint64",
    int8: "FieldType::Int8",
    int16: "FieldType::Int16",
    int32: "FieldType::Int32",
    int64: "FieldType::Int64",
    bool: "FieldType::Bool",
    enum: "FieldType::Enum",
    bitmap: "FieldType::Bitmap",
    string: "FieldType::String",
    bytes: "FieldType::Bytes",
    object: "FieldType::Object",
    array: "FieldType::Array"
  };
  return map[type] ?? "FieldType::Object";
}

function cppType(type: string): string {
  const map: Record<string, string> = {
    uint8: "std::uint8_t",
    uint16: "std::uint16_t",
    uint32: "std::uint32_t",
    uint64: "std::uint64_t",
    int8: "std::int8_t",
    int16: "std::int16_t",
    int32: "std::int32_t",
    int64: "std::int64_t",
    bool: "bool",
    string: "const char*",
    bytes: "const std::uint8_t*"
  };
  return map[type] ?? "std::uint32_t";
}

export async function emitCpp(spec: SpecModel, outDir: string): Promise<void> {
  await emitCppFiles(spec, path.join(outDir, "cpp"));
}

export async function emitCppFiles(spec: SpecModel, cppDir: string): Promise<void> {
  await Promise.all([
    writeTextFile(path.join(cppDir, "axtp_ids_generated.h"), emitIds(spec)),
    writeTextFile(path.join(cppDir, "axtp_schema_generated.h"), emitSchema(spec)),
    writeTextFile(path.join(cppDir, "axtp_method_registry_generated.h"), emitMethodRegistry(spec)),
    writeTextFile(path.join(cppDir, "axtp_event_registry_generated.h"), emitEventRegistry(spec)),
    writeTextFile(path.join(cppDir, "axtp_error_code_generated.h"), emitErrorRegistry(spec)),
    writeTextFile(path.join(cppDir, "axtp_capability_generated.h"), emitCapabilityRegistry(spec)),
    writeTextFile(path.join(cppDir, "axtp_tlv_codec_generated.h"), emitTlvSkeleton(spec)),
    writeTextFile(path.join(cppDir, "method_traits.h"), emitMethodTraits(spec)),
    writeTextFile(path.join(cppDir, "schema_codec.h"), emitSchemaCodec())
  ]);
}

function emitIds(spec: SpecModel): string {
  return `${banner}#pragma once
#include <cstdint>

namespace axtp {

${enumBlock("PayloadType", "std::uint8_t", spec.payloadTypes)}

${enumBlock("ControlOpcode", "std::uint8_t", spec.controlOpcodes)}

${enumBlock("RpcEncoding", "std::uint8_t", spec.rpcEncodings)}

${enumBlock("RpcBodyEncoding", "std::uint8_t", spec.rpcBodyEncodings)}

${enumBlock("RpcOp", "std::uint8_t", spec.rpcOps)}

${enumBlock("MethodId", "std::uint16_t", spec.methods)}

${enumBlock("EventId", "std::uint16_t", spec.events)}

${enumBlock("ErrorCode", "std::uint16_t", spec.errors)}

${enumBlock("CapabilityId", "std::uint16_t", spec.capabilities)}

} // namespace axtp
`;
}

function emitSchema(spec: SpecModel): string {
  const fieldArrays = spec.schemas.map((schema) => {
    const rows = schema.fields.map((field) =>
      `    { ${hex(field.id, 2)}, "${field.name}", ${fieldType(field.type)}, ${field.required}, ${field.min ?? 0}, ${field.max ?? 0} },`
    ).join("\n");
    return `inline constexpr FieldDescriptor k${cppName(schema.name)}Fields[] = {\n${rows}\n};`;
  }).join("\n\n");

  const descriptors = spec.schemas.map((schema) =>
    `inline constexpr SchemaDescriptor k${cppName(schema.name)}Schema = { "${schema.name}", k${cppName(schema.name)}Fields, ${schema.fields.length} };`
  ).join("\n");

  return `${banner}#pragma once
#include <cstddef>
#include <cstdint>

namespace axtp {

enum class FieldType : std::uint8_t {
    Uint8,
    Uint16,
    Uint32,
    Uint64,
    Int8,
    Int16,
    Int32,
    Int64,
    Bool,
    Enum,
    Bitmap,
    String,
    Bytes,
    Object,
    Array,
};

struct FieldDescriptor {
    std::uint8_t field_id;
    const char* name;
    FieldType type;
    bool required;
    std::uint32_t min_value;
    std::uint32_t max_value;
};

struct SchemaDescriptor {
    const char* name;
    const FieldDescriptor* fields;
    std::size_t field_count;
};

${fieldArrays}

${descriptors}

} // namespace axtp
`;
}

function emitMethodRegistry(spec: SpecModel): string {
  const rows = sortById(spec.methods).map((item) =>
    `    { ${hex(item.id)}, "${item.name}", "${item.domain}", "${item.requestSchema}", "${item.responseSchema}" },`
  ).join("\n");
  return `${banner}#pragma once
#include <cstddef>
#include <cstdint>

namespace axtp {

struct MethodDescriptor {
    std::uint16_t id;
    const char* name;
    const char* domain;
    const char* request_schema;
    const char* response_schema;
};

inline constexpr MethodDescriptor kMethodRegistry[] = {
${rows}
};

inline constexpr std::size_t kMethodRegistryCount = ${spec.methods.length};

} // namespace axtp
`;
}

function emitEventRegistry(spec: SpecModel): string {
  const rows = sortById(spec.events).map((item) =>
    `    { ${hex(item.id)}, "${item.name}", "${item.domain}", "${item.eventSchema}" },`
  ).join("\n");
  return `${banner}#pragma once
#include <cstddef>
#include <cstdint>

namespace axtp {

struct EventDescriptor {
    std::uint16_t id;
    const char* name;
    const char* domain;
    const char* event_schema;
};

inline constexpr EventDescriptor kEventRegistry[] = {
${rows}
};

inline constexpr std::size_t kEventRegistryCount = ${spec.events.length};

} // namespace axtp
`;
}

function emitErrorRegistry(spec: SpecModel): string {
  const rows = sortById(spec.errors).map((item) =>
    `    { ${hex(item.id)}, "${item.name}", "${item.domain}", ${item.retryable} },`
  ).join("\n");
  return `${banner}#pragma once
#include <cstddef>
#include <cstdint>

namespace axtp {

struct ErrorDescriptor {
    std::uint16_t id;
    const char* name;
    const char* domain;
    bool retryable;
};

inline constexpr ErrorDescriptor kErrorRegistry[] = {
${rows}
};

inline constexpr std::size_t kErrorRegistryCount = ${spec.errors.length};

} // namespace axtp
`;
}

function emitCapabilityRegistry(spec: SpecModel): string {
  const rows = sortById(spec.capabilities).map((item) =>
    `    { ${hex(item.id)}, "${item.name}", "${item.domain}", "${item.type}", "${item.schema ?? ""}" },`
  ).join("\n");
  return `${banner}#pragma once
#include <cstddef>
#include <cstdint>

namespace axtp {

struct CapabilityDescriptor {
    std::uint16_t id;
    const char* name;
    const char* domain;
    const char* type;
    const char* schema;
};

inline constexpr CapabilityDescriptor kCapabilityRegistry[] = {
${rows}
};

inline constexpr std::size_t kCapabilityRegistryCount = ${spec.capabilities.length};

} // namespace axtp
`;
}

function emitTlvSkeleton(spec: SpecModel): string {
  const fieldNamespaces = spec.schemas.map((schema) => emitFieldNamespace(schema)).join("\n\n");
  const structs = spec.schemas.map((schema) => emitStruct(schema)).join("\n\n");
  const declarations = spec.schemas.map((schema) => {
    const name = cppName(schema.name);
    return `bool Encode${name}(const ${name}& input, TlvWriter& writer, ErrorCode* error);\nbool Decode${name}(TlvReader& reader, ${name}* output, ErrorCode* error);`;
  }).join("\n\n");

  return `${banner}#pragma once
#include <cstdint>
#include "axtp_ids_generated.h"

namespace axtp {

class TlvWriter;
class TlvReader;

${fieldNamespaces}

${structs}

${declarations}

} // namespace axtp
`;
}

function emitMethodTraits(spec: SpecModel): string {
  const methods = sortById(spec.methods).map((method) => `template <>
struct MethodTraits<MethodId::${cppName(method.name)}> {
    using Request = ${cppName(method.requestSchema)};
    using Response = ${cppName(method.responseSchema)};
    static constexpr std::uint16_t id = static_cast<std::uint16_t>(MethodId::${cppName(method.name)});
    static constexpr const char* name = "${method.name}";
};`).join("\n\n");

  const events = sortById(spec.events).map((event) => `template <>
struct EventTraits<EventId::${cppName(event.name)}> {
    using Event = ${cppName(event.eventSchema)};
    static constexpr std::uint16_t id = static_cast<std::uint16_t>(EventId::${cppName(event.name)});
    static constexpr const char* name = "${event.name}";
};`).join("\n\n");

  return `${banner}#pragma once
#include <cstdint>

#include "generated/axtp_ids_generated.h"
#include "generated/axtp_tlv_codec_generated.h"

namespace axtp {

template <MethodId Id>
struct MethodTraits;

${methods}

template <EventId Id>
struct EventTraits;

${events}

} // namespace axtp
`;
}

function emitSchemaCodec(): string {
  return `${banner}#pragma once

#include <exception>
#include <string>

#include <boost/json.hpp>

#include "generated/method_traits.h"
#include "model/bytes.hpp"
#include "model/payload.hpp"

namespace axtp {

class SchemaCodec {
public:
    static RpcBodyEncoding bodyEncodingFor(RpcEncoding encoding) {
        if (encoding == RpcEncoding::JsonBinary) {
            return RpcBodyEncoding::Tlv8;
        }
        return RpcBodyEncoding::None;
    }

    template <MethodId Id>
    static Bytes encodeRequest(const typename MethodTraits<Id>::Request& request, RpcEncoding encoding) {
        if (encoding != RpcEncoding::Json) {
            return {};
        }
        const auto json = requestToJson<Id>(request);
        const auto text = boost::json::serialize(json);
        return Bytes(text.begin(), text.end());
    }

    template <MethodId Id>
    static typename MethodTraits<Id>::Response decodeResponse(const Bytes& bytes, RpcEncoding encoding) {
        typename MethodTraits<Id>::Response response{};
        if (encoding != RpcEncoding::Json || bytes.empty()) {
            return response;
        }
        try {
            const std::string text(bytes.begin(), bytes.end());
            const auto parsed = boost::json::parse(text);
            if (parsed.is_object()) {
                fillResponse<Id>(parsed.as_object(), response);
            }
        } catch (const std::exception&) {
        }
        return response;
    }

    template <EventId Id>
    static Bytes encodeEvent(const typename EventTraits<Id>::Event& event, RpcEncoding encoding) {
        if (encoding != RpcEncoding::Json) {
            return {};
        }
        const auto json = eventToJson<Id>(event);
        const auto text = boost::json::serialize(json);
        return Bytes(text.begin(), text.end());
    }

private:
    template <MethodId Id>
    static boost::json::object requestToJson(const typename MethodTraits<Id>::Request& request) {
        (void)request;
        return {};
    }

    template <MethodId Id>
    static void fillResponse(const boost::json::object& object, typename MethodTraits<Id>::Response& response) {
        (void)object;
        (void)response;
    }

    template <EventId Id>
    static boost::json::object eventToJson(const typename EventTraits<Id>::Event& event) {
        (void)event;
        return {};
    }
};

} // namespace axtp
`;
}

function emitFieldNamespace(schema: Schema): string {
  const rows = schema.fields.map((field) => `constexpr std::uint8_t ${cppConstName(field.name)} = ${hex(field.id, 2)};`).join("\n");
  return `namespace fields::${cppConstName(schema.name).toLowerCase()} {\n${rows}\n}`;
}

function emitStruct(schema: Schema): string {
  const fields = schema.fields.map((field) => {
    const type = cppType(field.type);
    const defaultValue = type === "bool" ? "false" : type.startsWith("const ") ? "nullptr" : "0";
    const has = field.required ? "" : `\n    bool has_${field.name} = false;`;
    return `    ${type} ${field.name} = ${defaultValue};${has}`;
  }).join("\n");
  return `struct ${cppName(schema.name)} {\n${fields}\n};`;
}
