import path from "node:path";
import type { CommonRegistryItem, Field, SpecModel } from "../models.js";
import { cppName, hex, sortById, writeTextFile } from "../util.js";

const banner = `// Generated by axtp-gen. Do not edit manually.\n`;

function tsName(name: string): string {
  const normalized = cppName(name);
  return normalized.length > 0 ? normalized : "Unknown";
}

function quote(value: string | undefined): string {
  return JSON.stringify(value ?? "");
}

function enumBlock(name: string, items: CommonRegistryItem[], width: number): string {
  const rows = sortById(items)
    .map((item) => `  ${tsName(item.name)} = ${hex(item.id, width)},`)
    .join("\n");
  return `export enum ${name} {\n${rows}\n}`;
}

function emitIds(spec: SpecModel): string {
  return `${banner}
${enumBlock("PayloadType", spec.payloadTypes, 2)}

${enumBlock("ControlOpcode", spec.controlOpcodes, 2)}

${enumBlock("RpcEncoding", spec.rpcEncodings, 2)}

${enumBlock("RpcBodyEncoding", spec.rpcBodyEncodings, 2)}

${enumBlock("RpcOp", spec.rpcOps, 2)}

${enumBlock("MethodId", spec.methods, 4)}

${enumBlock("EventId", spec.events, 4)}

${enumBlock("ErrorCode", spec.errors, 4)}

${enumBlock("CapabilityId", spec.capabilities, 4)}
`;
}

const kScalarTypes: Record<string, string> = {
  bool: "boolean",
  string: "string",
  bytes: "Uint8Array",
  uint8: "number",
  uint16: "number",
  uint32: "number",
  uint64: "number",
  int8: "number",
  int16: "number",
  int32: "number",
  int64: "number",
  float: "number",
  double: "number",
  enum: "string"
};

function scalarTypeName(type: string): string | undefined {
  return kScalarTypes[type];
}

// Maps a spec Field to its TypeScript type string. Handles scalar types,
// nested object references, and both object arrays (`schema:`) and scalar
// arrays (`array.item_type`).
function fieldTypeName(field: Field, knownSchemas: Set<string>): string {
  const isArray = field.type === "array" || field.repeated === true;
  if (isArray) {
    const itemName = field.array?.itemType ?? field.array?.itemSchema ?? field.schema ?? "";
    const itemScalar = scalarTypeName(itemName);
    const itemTs = itemScalar ?? (knownSchemas.has(itemName) ? tsName(itemName) : "unknown");
    return `${itemTs}[]`;
  }
  const scalar = scalarTypeName(field.type);
  if (scalar !== undefined) return scalar;
  if (knownSchemas.has(field.type)) return tsName(field.type);
  if (field.type === "object") return "Record<string, unknown>";
  return "unknown";
}

function collectSchemaNames(spec: SpecModel): Set<string> {
  return new Set(spec.schemas.map((schema) => schema.name));
}

function emitSchemas(spec: SpecModel): string {
  const knownSchemas = collectSchemaNames(spec);
  const blocks: string[] = ["export interface Empty {}"];
  const seen = new Set<string>(["Empty"]);
  for (const schema of spec.schemas) {
    const name = tsName(schema.name);
    if (seen.has(name)) continue;
    seen.add(name);
    const fieldLines = schema.fields.map((field) => {
      const optional = field.required ? "" : "?";
      // Field names map 1:1 to JSON wire keys, so keep the spec's original
      // (camelCase) name verbatim — do not PascalCase via tsName/cppName.
      return `  ${field.name}${optional}: ${fieldTypeName(field, knownSchemas)};`;
    });
    blocks.push(`export interface ${name} {\n${fieldLines.join("\n")}\n}`);
  }
  return `${banner}\n${blocks.join("\n\n")}\n`;
}

// emitRegistryMap: 产出单一事实源 registry.ts。
// 运行时 const 对象承载 id/status/bitOffset，类型用 keyof typeof 推导——
// 类型层方法/事件名集合与运行时注册集合是同一个对象，物理上不可能漂移
// （根除旧实现中 method_map interface 与 registry 数组双轨生成导致的不一致 BUG）。
function emitRegistryMap(spec: SpecModel): string {
  const methodRows = sortById(spec.methods)
    .map((method) => {
      const request = tsName(method.requestSchema || "Empty");
      const response = tsName(method.responseSchema || "Empty");
      const status = quote(method.status);
      const bit = method.bitOffset ?? 0;
      return `  ${quote(method.name)}: { id: ${hex(method.id, 4)}, status: ${status}, bitOffset: ${bit}, request: null as unknown as AxtpSchemas.${request}, response: null as unknown as AxtpSchemas.${response} },`;
    })
    .join("\n");
  const eventRows = sortById(spec.events)
    .map((event) => {
      const payload = tsName(event.eventSchema || "Empty");
      const status = quote(event.status);
      const bit = event.bitOffset ?? 0;
      return `  ${quote(event.name)}: { id: ${hex(event.id, 4)}, status: ${status}, bitOffset: ${bit}, payload: null as unknown as AxtpSchemas.${payload} },`;
    })
    .join("\n");
  return `${banner}
// 单一事实源：METHOD_REGISTRY / EVENT_REGISTRY。
// 类型（MethodName/EventName 等）直接 keyof typeof 推导自下方 const，
// 与运行时注册集合同源，不可漂移。
import type * as AxtpSchemas from "./schemas_generated.js";

export type MethodStatus = "stable" | "draft" | "mvp" | "deprecated" | "reserved";
export type EventStatus = "stable" | "draft" | "mvp" | "deprecated" | "reserved";

export const METHOD_REGISTRY = {
${methodRows}
} satisfies Record<string, { id: number; status: MethodStatus; bitOffset: number; request: unknown; response: unknown }>;

export const EVENT_REGISTRY = {
${eventRows}
} satisfies Record<string, { id: number; status: EventStatus; bitOffset: number; payload: unknown }>;

export type MethodName = keyof typeof METHOD_REGISTRY;
export type EventName = keyof typeof EVENT_REGISTRY;

export type MethodRequest<K extends MethodName> = (typeof METHOD_REGISTRY)[K]["request"];
export type MethodResponse<K extends MethodName> = (typeof METHOD_REGISTRY)[K]["response"];
export type EventPayload<K extends EventName> = (typeof EVENT_REGISTRY)[K]["payload"];

export type MethodId = (typeof METHOD_REGISTRY)[MethodName]["id"];
export type EventId = (typeof EVENT_REGISTRY)[EventName]["id"];
`;
}

// emitVersion: 产出 AXTP spec 兼容版本常量。
// AXTP_SPEC_VERSION 来自 spec 的 contract/registry/version.yaml 的 spec.version 字段，
// 这是 Hello.axtpVersion 的值——spec:205 定义为"AXTP spec compatibility authority"。
// 不是 SDK 软件版本（package.json version），而是协议规范版本。
function emitVersion(spec: SpecModel): string {
  const ver = spec.version as { spec?: { version?: string } } | undefined;
  const version = ver?.spec?.version ?? "1.0.0";
  return `${banner}// AXTP spec compatibility version（来自 contract/registry/version.yaml 的 spec.version）。\n// 这是 Hello.axtpVersion 的值——spec:205 定义为"AXTP spec compatibility authority"。\n// 不是 SDK 软件版本（package.json version），而是协议规范版本。\nexport const AXTP_SPEC_VERSION = "${version}";\n`;
}

export async function emitTs(spec: SpecModel, outDir: string): Promise<void> {
  await emitTsFiles(spec, path.join(outDir, "ts"));
}

export async function emitTsFiles(spec: SpecModel, tsDir: string): Promise<void> {
  // 只产出单一事实源 3 文件：axtp_ids（枚举）/ schemas（结构）/ registry（id+status+bitOffset，类型 keyof typeof 推导）。
  // 旧的双轨产物（registry_generated/method_map/event_map/capability_map）已停止产出——它们与 registry.ts 重复且运行时零引用。
  await Promise.all([
    writeTextFile(path.join(tsDir, "axtp_ids_generated.ts"), emitIds(spec)),
    writeTextFile(path.join(tsDir, "schemas_generated.ts"), emitSchemas(spec)),
    writeTextFile(path.join(tsDir, "registry.ts"), emitRegistryMap(spec)),
    writeTextFile(path.join(tsDir, "axtpVersion.ts"), emitVersion(spec))
  ]);
}
