// Generated by axtp-gen. Do not edit manually.
#pragma once
#include <cstdint>

namespace axtp {

enum class PayloadType : std::uint8_t {
    Control = 0x01,
};

enum class ControlOpcode : std::uint8_t {
    Open = 0x01,
};

enum class RpcEncoding : std::uint8_t {
    Binary = 0x02,
};

enum class RpcBodyEncoding : std::uint8_t {
    Tlv8 = 0x01,
};

enum class RpcOp : std::uint8_t {
    Request = 0x07,
};

enum class MethodId : std::uint16_t {
    AudioSetAlgorithmConfig = 0x0902,
};

enum class EventId : std::uint16_t {
    AudioAlgorithmConfigChanged = 0x0901,
};

enum class ErrorCode : std::uint16_t {
    Success = 0x0000,
};

enum class CapabilityId : std::uint16_t {
    AudioAlgorithm = 0x0901,
};

} // namespace axtp
