// Generated by axtp-gen. Do not edit manually.

export enum PayloadType {
  Control = 0x01,
}

export enum ControlOpcode {
  Open = 0x01,
}

export enum RpcEncoding {
  Binary = 0x02,
}

export enum RpcBodyEncoding {
  Tlv8 = 0x01,
}

export enum RpcOp {
  Request = 0x07,
}

export enum MethodId {
  AudioSetAlgorithmConfig = 0x0902,
}

export enum EventId {
  AudioAlgorithmConfigChanged = 0x0901,
}

export enum ErrorCode {
  Success = 0x0000,
}

export enum CapabilityId {
  AudioAlgorithm = 0x0901,
}
