import path from "node:path";
import type { CommonRegistryItem, SpecModel } from "../models.js";
import { cppName, hex, sortById, writeTextFile } from "../util.js";

const banner = `// Generated by axtp-gen. Do not edit manually.\n`;

function dartName(name: string): string {
  const normalized = cppName(name);
  if (normalized.length === 0) return "unknown";
  const value = `${normalized.charAt(0).toLowerCase()}${normalized.slice(1)}`;
  return value === "none" ? "noneValue" : value;
}

function quote(value: string | undefined): string {
  return JSON.stringify(value ?? "");
}

function enumBlock(name: string, items: CommonRegistryItem[], width: number): string {
  const rows = sortById(items)
    .map((item) => `  ${dartName(item.name)}(${hex(item.id, width)})`)
    .join(",\n");
  return `enum ${name} {
${rows};

  const ${name}(this.value);

  final int value;

  static ${name}? fromValue(int value) {
    for (final item in values) {
      if (item.value == value) return item;
    }
    return null;
  }
}`;
}

function emitIds(spec: SpecModel): string {
  return `${banner}
${enumBlock("PayloadType", spec.payloadTypes, 2)}

${enumBlock("ControlOpcode", spec.controlOpcodes, 2)}

${enumBlock("RpcEncoding", spec.rpcEncodings, 2)}

${enumBlock("RpcBodyEncoding", spec.rpcBodyEncodings, 2)}

${enumBlock("RpcOp", spec.rpcOps, 2)}

${enumBlock("MethodId", spec.methods, 4)}

${enumBlock("EventId", spec.events, 4)}

${enumBlock("ErrorCode", spec.errors, 4)}

${enumBlock("CapabilityId", spec.capabilities, 4)}
`;
}

function emitRegistries(spec: SpecModel): string {
  const methodRows = sortById(spec.methods)
    .map((item) =>
      `  MethodDescriptor(${hex(item.id)}, ${quote(item.name)}, ${quote(item.domain)}, ${quote(item.requestSchema)}, ${quote(item.responseSchema)})`
    )
    .join(",\n");
  const eventRows = sortById(spec.events)
    .map((item) =>
      `  EventDescriptor(${hex(item.id)}, ${quote(item.name)}, ${quote(item.domain)}, ${quote(item.eventSchema)})`
    )
    .join(",\n");
  const errorRows = sortById(spec.errors)
    .map((item) =>
      `  ErrorDescriptor(${hex(item.id)}, ${quote(item.name)}, ${quote(item.domain)}, ${item.retryable})`
    )
    .join(",\n");
  const capabilityRows = sortById(spec.capabilities)
    .map((item) =>
      `  CapabilityDescriptor(${hex(item.id)}, ${quote(item.name)}, ${quote(item.domain)}, ${quote(item.type)}, ${quote(item.schema)})`
    )
    .join(",\n");

  return `class MethodDescriptor {
  const MethodDescriptor(this.id, this.name, this.domain, this.requestSchema, this.responseSchema);

  final int id;
  final String name;
  final String domain;
  final String requestSchema;
  final String responseSchema;
}

class EventDescriptor {
  const EventDescriptor(this.id, this.name, this.domain, this.eventSchema);

  final int id;
  final String name;
  final String domain;
  final String eventSchema;
}

class ErrorDescriptor {
  const ErrorDescriptor(this.id, this.name, this.domain, this.retryable);

  final int id;
  final String name;
  final String domain;
  final bool retryable;
}

class CapabilityDescriptor {
  const CapabilityDescriptor(this.id, this.name, this.domain, this.type, this.schema);

  final int id;
  final String name;
  final String domain;
  final String type;
  final String schema;
}

const kMethodRegistry = <MethodDescriptor>[
${methodRows}
];

const kEventRegistry = <EventDescriptor>[
${eventRows}
];

const kErrorRegistry = <ErrorDescriptor>[
${errorRows}
];

const kCapabilityRegistry = <CapabilityDescriptor>[
${capabilityRows}
];

class RegistryLookup {
  const RegistryLookup._();

  static int? methodIdByName(String name) {
    for (final descriptor in kMethodRegistry) {
      if (descriptor.name == name) return descriptor.id;
    }
    return null;
  }

  static MethodDescriptor? methodById(int id) {
    for (final descriptor in kMethodRegistry) {
      if (descriptor.id == id) return descriptor;
    }
    return null;
  }

  static int? eventIdByName(String name) {
    for (final descriptor in kEventRegistry) {
      if (descriptor.name == name) return descriptor.id;
    }
    return null;
  }

  static EventDescriptor? eventById(int id) {
    for (final descriptor in kEventRegistry) {
      if (descriptor.id == id) return descriptor;
    }
    return null;
  }

  static ErrorDescriptor? errorByCode(Object code) {
    final value = code is ErrorCode ? code.value : code as int;
    for (final descriptor in kErrorRegistry) {
      if (descriptor.id == value) return descriptor;
    }
    return null;
  }
}

class MethodRegistryEntry {
  const MethodRegistryEntry(this.id, this.name);

  final int id;
  final String name;
}

class MethodRegistry {
  MethodRegistry();

  factory MethodRegistry.fromGeneratedDefaults() {
    final registry = MethodRegistry();
    for (final method in kMethodRegistry) {
      registry.addMethod(method.id, method.name);
    }
    return registry;
  }

  final Map<String, int> _nameToId = <String, int>{};
  final Map<int, String> _idToName = <int, String>{};

  void addMethod(int methodId, String methodName) {
    final existingName = _idToName[methodId];
    if (existingName != null) {
      _nameToId.remove(existingName);
    }
    final existingId = _nameToId[methodName];
    if (existingId != null) {
      _idToName.remove(existingId);
    }
    _nameToId[methodName] = methodId;
    _idToName[methodId] = methodName;
  }

  int? findMethodId(String methodName) => _nameToId[methodName];

  String? findMethodName(int methodId) => _idToName[methodId];

  bool containsMethod(Object method) {
    if (method is int) return _idToName.containsKey(method);
    if (method is String) return _nameToId.containsKey(method);
    return false;
  }

  List<MethodRegistryEntry> entries() {
    final ids = _idToName.keys.toList()..sort();
    return [
      for (final id in ids) MethodRegistryEntry(id, _idToName[id]!)
    ];
  }
}
`;
}

export async function emitDart(spec: SpecModel, outDir: string): Promise<void> {
  await emitDartFiles(spec, path.join(outDir, "dart"));
}

export async function emitDartFiles(spec: SpecModel, dartDir: string): Promise<void> {
  await writeTextFile(
    path.join(dartDir, "axtp_registry_generated.dart"),
    `${emitIds(spec)}\n${emitRegistries(spec)}`
  );
}
