import path from "node:path";
import type { CommonRegistryItem, SpecModel } from "../models.js";
import { cppName, hex, sortById, writeTextFile } from "../util.js";

const banner = `// Generated by axtp-gen. Do not edit manually.\n`;

function tsName(name: string): string {
  const normalized = cppName(name);
  return normalized.length > 0 ? normalized : "Unknown";
}

function quote(value: string | undefined): string {
  return JSON.stringify(value ?? "");
}

function enumBlock(name: string, items: CommonRegistryItem[], width: number): string {
  const rows = sortById(items)
    .map((item) => `  ${tsName(item.name)} = ${hex(item.id, width)},`)
    .join("\n");
  return `export enum ${name} {\n${rows}\n}`;
}

function emitIds(spec: SpecModel): string {
  return `${banner}
${enumBlock("PayloadType", spec.payloadTypes, 2)}

${enumBlock("ControlOpcode", spec.controlOpcodes, 2)}

${enumBlock("RpcEncoding", spec.rpcEncodings, 2)}

${enumBlock("RpcBodyEncoding", spec.rpcBodyEncodings, 2)}

${enumBlock("RpcOp", spec.rpcOps, 2)}

${enumBlock("MethodId", spec.methods, 4)}

${enumBlock("EventId", spec.events, 4)}

${enumBlock("ErrorCode", spec.errors, 4)}

${enumBlock("CapabilityId", spec.capabilities, 4)}
`;
}

function emitRegistries(spec: SpecModel): string {
  const methodRows = sortById(spec.methods)
    .map((item) =>
      `  { id: ${hex(item.id)}, name: ${quote(item.name)}, domain: ${quote(item.domain)}, requestSchema: ${quote(item.requestSchema)}, responseSchema: ${quote(item.responseSchema)} },`
    )
    .join("\n");
  const eventRows = sortById(spec.events)
    .map((item) =>
      `  { id: ${hex(item.id)}, name: ${quote(item.name)}, domain: ${quote(item.domain)}, eventSchema: ${quote(item.eventSchema)} },`
    )
    .join("\n");
  const errorRows = sortById(spec.errors)
    .map((item) =>
      `  { id: ${hex(item.id)}, name: ${quote(item.name)}, domain: ${quote(item.domain)}, retryable: ${item.retryable} },`
    )
    .join("\n");
  const capabilityRows = sortById(spec.capabilities)
    .map((item) =>
      `  { id: ${hex(item.id)}, name: ${quote(item.name)}, domain: ${quote(item.domain)}, type: ${quote(item.type)}, schema: ${quote(item.schema)} },`
    )
    .join("\n");

  return `${banner}
import { ErrorCode } from "./axtp_ids_generated.js";

export interface MethodDescriptor {
  id: number;
  name: string;
  domain: string;
  requestSchema: string;
  responseSchema: string;
}

export interface EventDescriptor {
  id: number;
  name: string;
  domain: string;
  eventSchema: string;
}

export interface ErrorDescriptor {
  id: number;
  name: string;
  domain: string;
  retryable: boolean;
}

export interface CapabilityDescriptor {
  id: number;
  name: string;
  domain: string;
  type: string;
  schema: string;
}

export const kMethodRegistry = [
${methodRows}
] as const satisfies readonly MethodDescriptor[];

export const kEventRegistry = [
${eventRows}
] as const satisfies readonly EventDescriptor[];

export const kErrorRegistry = [
${errorRows}
] as const satisfies readonly ErrorDescriptor[];

export const kCapabilityRegistry = [
${capabilityRows}
] as const satisfies readonly CapabilityDescriptor[];

export class RegistryLookup {
  static methodIdByName(name: string): number | undefined {
    return kMethodRegistry.find((descriptor) => descriptor.name === name)?.id;
  }

  static methodById(id: number): MethodDescriptor | undefined {
    return kMethodRegistry.find((descriptor) => descriptor.id === id);
  }

  static eventIdByName(name: string): number | undefined {
    return kEventRegistry.find((descriptor) => descriptor.name === name)?.id;
  }

  static eventById(id: number): EventDescriptor | undefined {
    return kEventRegistry.find((descriptor) => descriptor.id === id);
  }

  static errorByCode(code: ErrorCode | number): ErrorDescriptor | undefined {
    const value = Number(code);
    return kErrorRegistry.find((descriptor) => descriptor.id === value);
  }
}

export interface MethodRegistryEntry {
  id: number;
  name: string;
}

export class MethodRegistry {
  private readonly nameToId = new Map<string, number>();
  private readonly idToName = new Map<number, string>();

  static fromGeneratedDefaults(): MethodRegistry {
    const registry = new MethodRegistry();
    for (const method of kMethodRegistry) {
      registry.addMethod(method.id, method.name);
    }
    return registry;
  }

  addMethod(methodId: number, methodName: string): void {
    const existingName = this.idToName.get(methodId);
    if (existingName !== undefined) {
      this.nameToId.delete(existingName);
    }
    const existingId = this.nameToId.get(methodName);
    if (existingId !== undefined) {
      this.idToName.delete(existingId);
    }
    this.nameToId.set(methodName, methodId);
    this.idToName.set(methodId, methodName);
  }

  findMethodId(methodName: string): number | undefined {
    return this.nameToId.get(methodName);
  }

  findMethodName(methodId: number): string | undefined {
    return this.idToName.get(methodId);
  }

  containsMethod(method: number | string): boolean {
    return typeof method === "number" ? this.idToName.has(method) : this.nameToId.has(method);
  }

  entries(): MethodRegistryEntry[] {
    return [...this.idToName.entries()]
      .sort(([lhs], [rhs]) => lhs - rhs)
      .map(([id, name]) => ({ id, name }));
  }
}
`;
}

export async function emitTs(spec: SpecModel, outDir: string): Promise<void> {
  await emitTsFiles(spec, path.join(outDir, "ts"));
}

export async function emitTsFiles(spec: SpecModel, tsDir: string): Promise<void> {
  await Promise.all([
    writeTextFile(path.join(tsDir, "axtp_ids_generated.ts"), emitIds(spec)),
    writeTextFile(path.join(tsDir, "registry_generated.ts"), emitRegistries(spec))
  ]);
}
